export { ORCA_PI_VERSION, TARGET_ORCA_PLUGIN_API, TARGET_ORCA_APP_VERSION } from "./version.js";
export {
  doctor,
  formatDoctorReport,
  parseOrcaStatusJson,
  parseVersionFromText,
  PI_INSTALL_HINT,
  ORCA_INSTALL_HINT,
  type DoctorCheck,
  type DoctorExecutable,
  type DoctorReport,
} from "./doctor.js";
export { createNodeRunner } from "./nodeRunner.js";
export {
  qualifiedPluginKey,
  validatePluginManifest,
  type ManifestValidation,
  type OrcaPluginManifest,
  type OrcaPluginCommandContribution,
  type OrcaPluginPanelContribution,
  type OrcaPluginEventContribution,
  type OrcaPluginCapability,
  type OrcaPluginKeybindingContribution,
  type OrcaPluginLanguagePackContribution,
  type OrcaPluginPathContribution,
  type PluginCapabilityKind,
  type PluginCommandContext,
  type PluginEventName,
} from "./pluginManifest.js";
export {
  ExecutableNotFoundError,
  isNotFoundError,
  type CommandResult,
  type ProcessRunner,
} from "./runner.js";
export {
  BUILTIN_PROFILE_DEFAULTS,
  BUILTIN_TOOLS,
  MODEL_PATTERN,
  MODEL_THINKING_SUFFIX_PATTERN,
  PROFILE_NAME_PATTERN,
  RESERVED_PROFILE_NAMES,
  PROVIDER_PATTERN,
  SESSION_MODES,
  THINKING_LEVELS,
  TOOL_NAME_PATTERN,
  getCandidateConfigPaths,
  getProjectProfilesPath,
  getUserProfilesPath,
  listProfileNames,
  loadMergedProfiles,
  loadProfilesFile,
  mergeValidatedDocuments,
  normalizeProjectRelativePath,
  parseAndValidateProfilesText,
  parseProfilesText,
  ProfileLoadError,
  ProfileResolveError,
  ProfileValidationError,
  resolveAllProfiles,
  resolveProfile,
  validateProfileOverrides,
  validateProfilesDocument,
  type BuiltinProfileDefaults,
  type PiProfileInput,
  type PiProfilesDocumentInput,
  type ProfileIssue,
  type ProfileOverrides,
  type ProfileResolveErrorCode,
  type ResolveProfileOptions,
  type ResolvedPiProfile,
  type SessionMode,
  type ThinkingLevel,
  type ValidatedPiProfile,
  type ValidatedProfilesDocument,
} from "./profile/index.js";
